1) Swap two numbers using 3rd variable

In [1]:
#We swap two numbers by storing the value of one number in a thirdmvariable,
# Assign the value of the second number to the first number,
# and then assigning the value stored in the third variable to the second number.

num1 = int(input('Enter the first number num1:-'))
num2 = int(input('Enter the second number num2:-'))

print('Original value of num1:-', num1 ,'and num2:-',num2)

third_var = 0

if num1 != num2:
  third_var = num1
  num1 = num2
  num2 = third_var

print('Swapped numbers of num1:-',num1, 'and num2:-', num2)



Enter the first number num1:-6
Enter the second number num2:-2
Original value of num1:- 6 and num2:- 2
Swapped numbers of num1:- 2 and num2:- 6


2) Swap two numbers without using 3rd variable.


In [2]:
#add both numbers and store the result in the first one.
#Next subtract the second variable from the first one and save the result for the second one.

num1 = int(input('Enter the first number num1:-'))
num2 = int(input('Enter the second number num2:-'))

print('Original value of num1:-', num1 ,'and num2:-',num2)

if num1 != num2:
  num1 = num1 + num2
  num2 = num1 - num2
  num1 = num1 - num2


  print('Swapped numbers of num1:-',num1, 'and num2:-', num2)


Enter the first number num1:-6
Enter the second number num2:-7
Original value of num1:- 6 and num2:- 7
Swapped numbers of num1:- 7 and num2:- 6


3) Remove duplicate elements from a list without converting to tuple

In [3]:
# using set() to remove duplicated from list
lst1 = [1,1,2,3,4,5,5,6,7,8,11,56,33,11,5,7,33]
print('Original list before removing:-', lst1)

lst1 = list(set(lst1))

print('After removing duplicate elements from the list', lst1)



Original list before removing:- [1, 1, 2, 3, 4, 5, 5, 6, 7, 8, 11, 56, 33, 11, 5, 7, 33]
After removing duplicate elements from the list [1, 2, 3, 4, 5, 6, 7, 8, 33, 11, 56]


4) Write a program to find greatest common divisor (GCD) or highest common factor (HCF) of given two numbers

In [4]:

num1 = int(input('Enter first number:-'))
num2 = int(input('Enter Second number:-'))

def greatest_common_divisor(num1, num2):
  for i in range(1, min(num1,num2)+1):
    if num1 % i == 0 and num2 % i == 0:
      common_divisor = i
  return common_divisor

result = greatest_common_divisor(num1, num2)
print('The greatest common divisor of', num1,'and', num2, 'is:-', result)




Enter first number:-24
Enter Second number:-32
The greatest common divisor of 24 and 32 is:- 8


5) Write a loop to print following series:-
10, 20, 30,  …………………, 300

In [5]:
n = 10
k = 0
series = []

def print_series (k):
  for i in range(1,31):
    k = n * i
    series.append(k)
  return series

def show_series(k):
  series = print_series(k)
  return ','.join(map(str, series))

result = show_series(k)
print(result)



10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180,190,200,210,220,230,240,250,260,270,280,290,300


In [6]:
nums = [10, 20, 30, 300]

for i in range(len(nums)):
  num = nums[i]
  separator = ", "
  if num == 10:
    print(num,  end=separator)
  elif num == 20:
    print(num, end = separator)
  elif num == 30:
    print(num , end = separator)
  else:
    print('............,', num)



10, 20, 30, ............, 300


6) Write a loop to print following series
105,98,91,………………………,7


In [7]:
n = 7
series = []


def print_series (k):
  for i in range(15,0,-1):
    k = n * i
    series.append(k)
    k += 1
  return series

def show_series(k):
  series = print_series(k)
  return ','.join(map(str, series))

k = 1


answer = show_series(k)
print(answer)


105,98,91,84,77,70,63,56,49,42,35,28,21,14,7


In [3]:
n = 105

while n > 7:
    print(n, end=", ")
    n -= 7

print("7")


105, 98, 91, 84, 77, 70, 63, 56, 49, 42, 35, 28, 21, 14, 7


7) Write a program to print number names of digits in a number like

SAMPLE INPUT 231 		SAMPLE OUTPUT TWO THREE ONE

In [4]:
name_for_digit ={'0':'Zero',
                 '1':'One',
                 '2': 'TWO',
                 '3': 'THREE',
                 '4': 'FOUR',
                 '5': 'FIVE',
                 '6': 'SIX',
                 '7': 'SEVEN',
                 '8': 'EIGHT',
                 '9': 'NINE'
}
num = input('Enter a number:-')

result =''
for digit in num:
  result += name_for_digit[digit] + ''

print('Number in words:', result.strip())

Enter a number:-6
Number in words: SIX


8. Write a program to print Fibonacci series till n terms take n =50

In [3]:
n = 50

a = 0
b = 1
print(a, b, end=' ')
for i in range(n):
  c = a + b
  print(c, end=' ')
  a = b
  b = c

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170 1836311903 2971215073 4807526976 7778742049 12586269025 20365011074 

9. Write a program to print factorial of a number

In [18]:
n=int(input("Enter the Number for factorial"))
def factorial(num):
  factorial = 1
  while num > 1:
    factorial *= num
    num -= 1
  return factorial

facts = factorial(n)
print(f"The factorial of {n} is: {facts}")

Enter the Number for factorial6
The factorial of 6 is: 720


10. Write a program to check if a number is Armstrong or not

In [23]:
def armstrong_number(number):
  num_str = str(number) #Converting the number to astring to count its digits.
  num_digits = len(num_str) #Calculate the number of digits
  sum_of_digits = 0 #Initializing a variable to store the sum of digits.

  for digit_str in num_str: #Iterating through each digit in the number
    digit = int(digit_str)
    sum_of_digits += digit ** num_digits

  if sum_of_digits == number: #Check if the sum of digits is equal to the original number
    return True
  else:
    return False

num = int(input('Enter a number:-'))

if armstrong_number(num): #Check if it is an Armstrong number.
  print(num, 'is an Armstrong number.')
else:
  print(num, 'is not an Armstrong number.')



Enter a number:-123
123 is not an Armstrong number.


11.  Write a program to convert binary to decimal

In [44]:
binary_strng = input('Enter a binary number:-')
decimal_num = 0
pos = len(binary_strng)-1

for digit in binary_strng:
  if digit == '1':
    decimal_num += 2 ** pos
  pos -= 1

print('Decimal number of', binary_strng, 'is',decimal_num,'.')

Enter a binary number:-10110101010
Decimal number of 10110101010 is 1450 .


12. Write a program to convert decimal to binary

In [61]:
decimal_strng= int(input('Enter a decimal number:-'))
binary_num = []

if decimal_strng == 0:
  binary_num.append(0)
else:
  while decimal_strng > 0:
    reminder = decimal_strng % 2
    binary_num.append(reminder)
    decimal_strng = decimal_strng//2

binary_num.reverse()
binary_num = ''.join(map(str, binary_num))
print('The binary digits is:-',binary_num)


Enter a decimal number:-56
The binary digits is:- 111000


13. Write a program to check if number is palindrome on not (Without converting to string)

In [49]:
def if_palindrome(num):
  org_num = num
  rev_num = 0 #Initalizing a variable to store the reversed number

  while num > 0:
    digit = num % 10 # Get the last digit of the number
    rev_num = rev_num * 10 + digit
    num = num // 10 #Removing the last digit from the number

  if org_num == rev_num:
    return True
  else:
    return False

num = int(input('Enter a number:-'))

if if_palindrome(num):
  print(num, 'is a palindrome.')
else:
  print(num, 'is not a palindrome.')



Enter a number:-121
121 is a palindrome.


14. Write a program to print all numbers which are divisible by 13 but not by 3 between 100 and 500

In [59]:
number =[]
for i in range(100,501):
  if i % 13 == 0 and i % 3 != 0:
    number.append(i)

for num in number:
  print(num)




104
130
143
169
182
208
221
247
260
286
299
325
338
364
377
403
416
442
455
481
494


15. Write a Python program to convert temperatures to and from Celsius and Fahrenheit.

In [63]:
def C_to_F(celsius):
  fahrenheit = (celsius * 9/5) + 32
  return fahrenheit

def F_to_C(fahrenheit):
  celsius =  (fahrenheit - 32) * 5/9
  return celsius

while True:
  print('1. Convert Celsius to Fahrenheit')
  print('2. Convert Fahrenheit to Celsius')
  print('3. Quit')

  choice = int(input('Enter your choice (1/2/3):'))

  if choice == 1:
    celsius = float(input('Enter temperature in Celsius:-'))
    fahrenheit = C_to_F(celsius)
    print(celsius,'°C is equal to',fahrenheit,'°F.')

  elif choice == 2:
    fahrenheit = float(input('Enter tempreture in Fahrenheit:-'))
    celsius = F_to_C(fahrenheit)
    print(fahrenheit,'°F is equal to', celsius,'°C.')

  elif choice == 3:
    print('Quit! GoodBye!')
    break
  else:
    print('Invalid choice!')




1. Convert Celsius to Fahrenheit
2. Convert Fahrenheit to Celsius
3. Quit
Enter your choice (1/2/3):2
Enter tempreture in Fahrenheit:-159
159.0 °F is equal to 70.55555555555556 °C.
1. Convert Celsius to Fahrenheit
2. Convert Fahrenheit to Celsius
3. Quit
Enter your choice (1/2/3):3
Quit! GoodBye!


16. Write a Python program that takes two digits m (row) and n (column) as input and generates a two-dimensional array. The element value in the i-th row and j-th column of the array should be i*j. else it will be 0

In [6]:
import numpy as np

def generate_array(m, n):
  result = np.zeros((m, n), dtype=int)
  for i in range(m):
    for j in range(n):
      result[i][j] = i * j

  return result

m = int(input("Enter the number of rows (m): "))
n = int(input("Enter the number of columns (n): "))

result_array = generate_array(m, n)
print(result_array)


Enter the number of rows (m): 6
Enter the number of columns (n): 6
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]
 [ 0  5 10 15 20 25]]


17. Write a Python program that accepts a string and calculates the number of digits and letters.
Sample Data: Python 3.2
Expected Output:
Letters 6
Digits 2


In [5]:
string = input('Enter a string:-')
letter_count = 0
digit_count = 0

for letters in string:
  if 'a' <= letters <= 'z' or 'A' <= letters <= 'Z': #checking if the character is in betn a-z or A-Z.
    letter_count += 1
  elif '0' <= letters <= '9': #checking if num is in betn 0-9.
    digit_count += 1

print('Letters count is', letter_count)
print('Digits count is', digit_count)


Enter a string:-2ne1
Letters count is 2
Digits count is 2


18. Print all possible combination for a string or a word
Sample input “ABC”
Sample output
BAC
CAB
CBA
ACB
BCA


In [7]:
def for_combinations(string, current_combination = ' '):
  if len(string) == 0:
    print(current_combination)
  else:
    for i in range(len(string)):
      remaining = string[:i] + string[i+1:]
      for_combinations(remaining, current_combination + string[i])

string = input('Enter a string:')
for_combinations(string)

Enter a string:cr7
 cr7
 c7r
 rc7
 r7c
 7cr
 7rc



19.  Write a Python program to check if a triangle is equilateral, isosceles or scalene. Take 3 inputs for each side

Note :
An equilateral triangle is a triangle in which all three sides are equal.
A scalene triangle is a triangle that has three unequal sides.
An isosceles triangle is a triangle with (at least) two equal sides.


In [8]:
side1 = float(input('Enter a length of the side1:-'))
side2 = float(input('Enter a length of the side2:-'))
side3 = float(input('Enter a length of the side3:-'))

if side1 + side2 > side3 and side2 + side3 > side1 and side1 + side3 > side2:
  if side1 == side2 == side3:
    print('The triangle is Equilateral triangle')
  elif side1 == side2 or side2 == side3 or side1 == side3:
    print('The triangle is isosceles traingle')
  else:
    print('The traingle is scalene')
else:
  print('This doesnot form a valid traingle')




Enter a length of the side1:-1
Enter a length of the side2:-2
Enter a length of the side3:-3
This doesnot form a valid traingle


20. Write a Python program to get the next day of a given date.
Expected Output:
Input a year: 2016                                                      
Input a month [1-12]: 08                                                
Input a day [1-31]: 23                                                  
The next date is [yyyy-mm-dd] 2016-8-24  


In [2]:
year = int(input('Enter a year:-'))
month = int(input('Enter a month[1-12]:-'))
day = int(input('Enter a day[1-31]:-'))

if 1 <= month <= 12 and 1 <= day <= 31:
  if month in {1, 3, 5, 7, 8, 10, 12}:
    max_day = 31

  elif month in {4,6,9,11}:
    max_day = 30

  else:
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
      max_day = 29
    else:
      max_day = 28

  if 1 <= day <= max_day:
    if day < max_day:
      day += 1
    else:
      day = 1
      if month < 12:
        month += 1
      else:
        month = 1
        year += 1
    print('The next date is [yyyy-mm-dd] {}-{}-{}'.format(year, month,day))
  else:
    print('Invalid day for the selected month.')
else:
  print('Invalid input. Please enter a valid month and day.')





Enter a year:-2000
Enter a month[1-12]:-4
Enter a day[1-31]:-23
The next date is [yyyy-mm-dd] 2000-4-24
